config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "kittens#index"
  resources :kittens
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :softness, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [ :show, :edit, :update, :destroy ]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json  { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Kitten was successfully created."
      redirect_to kittens_path
    else
      flash.now[:errors] = @kitten.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json  { render json: @kitten }
    end
  end

  def edit; end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = "Kitten was successfully updated."
      redirect_to kittens_path
    else
      flash.now[:errors] = @kitten.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy
    flash[:success] = "Kitten was successfully ******."
    redirect_to kittens_path
  end

  private

  def set_kitten
    @kitten = Kitten.find_by(id: params[:id])
    unless @kitten
      flash[:errors] = "Kitten not found."
      redirect_to kittens_path
    end
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<h3><%= kitten.name %><h3>
<p><strong>Age: </strong><%= kitten.age %></p>
<p><strong>Cuteness: </strong><%= kitten.cuteness %></p>
<p><strong>Softness: </strong><%= kitten.softness %></p>

app/views/kittens/_kitten_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>

  <div>
    <%= form.label :age%>
    <%= form.number_field :age%>
  </div>

  <div>
    <%= form.label :cuteness, "Cuteness Level (1-10)"%>
    <%= form.number_field :cuteness%>
  </div>  

  <div>
    <%= form.label :softness, "Softness Level (1-10)"%>
    <%= form.number_field :softness%>
  </div>  

  <div>
    <%= form.submit "Save Kitten"%>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten: </h1>

<% if @kitten.errors.any? %>
  <div class="alert alert-error">
    <ul>
      <% @kitten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div>
  <%= render "kitten_form", kitten: @kitten %>
  <%= link_to "****** Kitten", kitten_path(@kitten), method: :delete%>
</div>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<%= link_to "New Kitten", new_kitten_path %>

<div>
  <% if flash.present? %>
    <% flash.each do |key, msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
</div>

<br>

<div>
  <% @kittens.each_with_index do |kitten, idx| %>
    <div>
      <h2>Kitten #<%= idx + 1 %></h2>
      <div><%= render "kitten", kitten: kitten%></div>
      <%= link_to "Edit Kitten", edit_kitten_path(kitten) %>
      <%= link_to "Kitten's Details", kitten_path(kitten) %>
      <hr>
    </div>
  <% end %>
</div>

app/views/kittens/new.html.erb
<h1>New Kitten: </h1>

<% if @kitten.errors.any? %>
  <div class="alert alert-error">
    <ul>
      <% @kitten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= render "kitten_form", kitten: @kitten %>
</div>

app/views/kittens/show.html.erb
<div>
  <%= render "kitten", kitten: @kitten %>
  <%= link_to "****** Kitten", kitten_path(@kitten), data: { turbo_method: :delete}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>